MVCforHRSystem/Models/UserView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HR.Website.Models
{
    public class UserView
    {
        [Display(Name = "Id")]
        public int UserID { get; set; }
        [Display(Name = "First Name")]
        public string Name { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Display(Name = "Job Title")]
        public string JobTitle { get; set; }
        [Display(Name = "Phone Number")]
        public string Mobile { get; set; }
        [Display(Name = "Email Address")]
        public string Email { get; set; }

    }
}

MVCforHRSystem/Controllers/VacationController.cs
using HR.Website.Infrastructure;
using HR.Website.Models;
using HR.Website.Models.Enums;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace HR.Website.Controllers
{
    public class VacationController : BaseController
    {
        [CustomAuthorizationFilter("0", "1")]
        public ActionResult DisplayVacations()
        {
            return View();
        }
        [CustomAuthorizationFilter("1")]
        public ActionResult AddNewVacation()
        {

            return View();
        }
        public ActionResult UpdateVacation(int id = 0)
        {
            try
            {
                if (id != 0)
                {
                    HttpResponseMessage response = GlobalVariable.ApiClient.GetAsync($"vacations/GetVacationById/{id}").Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var vacation = response.Content.ReadAsAsync<VacationInsertAndEdit>().Result;

                        return View(vacation);
                    }

                }
            }
            catch (Exception ex) { 
                GlobalVariable.log.Error(ex);
                ViewBag.Message = $"Oops! Something went wrong, please try again later"; }
            return View();
        }
        // GET: Vacation
        [HandleError]
        public ActionResult Vacation()
        {
            PagingModel paging = new PagingModel
            {
                // server side parameter
                DisplayStart = Convert.ToInt32(Request["start"]),
                DisplayLength = Convert.ToInt32(Request["length"]),
                SearchValue = Request["search[value]"],
                SortCol = Request["columns[" + Request["order[0][column]"] + "][name]"],
                SortDir = Request["order[0][dir]"]
            };

            List<VacationView> vacations = null;
            var userID = Session["UserID"];
            var role = Convert.ToInt32(Session["Role"]);
            try
            {
                if (ModelState.IsValid)
                {
                    HttpResponseMessage response = GlobalVariable.ApiClient.PostAsJsonAsync<PagingModel>($"vacations/GetVacations?id={userID}&role={role}", paging).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var content = response.Content.ReadAsAsync<PageRecord<VacationView>>().Result;
                        vacations = content.Data;
                        int totalRecord = content.TotalRecord;
                        int totalFilteredRecord = content.TotalFilteredRecord;

                        var result = from c in vacations
                                     select new[]
                            { Convert.ToString(c.VacationID),
                        c.Name, c.LastName, Convert.ToString(c.Type), Convert.ToString(c.StartDate),
                        Convert.ToString(c.EndDate), Convert.ToString(c.Status), c.Attatchment, c.Description ,c.RejectionReason};
                        return Json(new { aaData = result.ToArray(), recordsTotal = totalRecord, draw = Request["draw"], recordsFiltered = totalFilteredRecord }, JsonRequestBehavior.AllowGet);

                    }
                }
            }
            catch (Exception ex) {     
                GlobalVariable.log.Error(ex);
                return Json(new { aaData = string.Empty.ToArray(), JsonRequestBehavior.AllowGet });
            }
            return View("DisplayVacations");
        }
        public bool CheckContentType(string contentType) {
            return contentType.Equals("application/pdf");
        }
        public ActionResult LoadFile(string path)
        {
        
            //path = Path.Combine(@"C:\Users\Ghadir SSD\source\repos\HR.Website\HR.Website\Content\Files");

            return File(path, "application/pdf");

        }
        
        [HttpPost]
        [CustomAuthorizationFilter("1")]
        public ActionResult AddVacation(VacationView vacation, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                vacation.EmployeeID = Convert.ToInt32(Session["UserID"]);
                if (file != null && !CheckContentType(file.ContentType))
                {
                    return Json(new { success = false, message = "File format is not supported, please upload a PDF file!" }, JsonRequestBehavior.AllowGet);
                }
                else if (file != null && file.ContentLength > 0)
                {
                    try
                    {
                        string path = vacation.Attatchment;

                        path = Path.Combine(Server.MapPath("/Content/Files"),
                                                   Path.GetFileName(file.FileName));
                        file.SaveAs(path);
                        vacation.Attatchment = path;

                        ViewBag.Message = "File uploaded successfully";
                    }
                    catch (Exception ex)
                    {
                        GlobalVariable.log.Error(ex);
                       // ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                //else
                //{
                //    ViewBag.Message = "You have not specified a file.";
                //}
                try
                {
                    HttpResponseMessage response = GlobalVariable.ApiClient.PostAsJsonAsync<VacationView>("vacations/PostVacation", vacation).Result;

                    if (response.IsSuccessStatusCode)
                    {
                        return Json(new { success = true, message = "Added Successfully" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        var totalDays = (vacation.EndDate - vacation.StartDate).TotalDays;
                        var totalHours = (vacation.EndDate - vacation.StartDate).TotalHours;
                        if (Math.Abs(totalDays) > 14 && vacation.Type == Types.Annual)
                        {
                            return Json(new { success = false, message = "Only 14 days or less are allowed for Annual vacation!" }, JsonRequestBehavior.AllowGet);
                        }
                        else if (Math.Abs(totalHours) > 8 && vacation.Type == Types.Leave)
                        {
                            return Json(new { success = false, message = "Only 8 hours or less are allowed for Leave Request!" }, JsonRequestBehavior.AllowGet);
                        }
                        return Json(new { success = false, message = "You have exceeded the limit of annual vacation days" }, JsonRequestBehavior.AllowGet);

                        // return Json(new { success = false, message = "Only 14 days or less are allowed for Annual vacation!" }, JsonRequestBehavior.AllowGet);
                    }
                }
                catch (Exception ex) { 
                    GlobalVariable.log.Error(ex.Message); 
                    return Json(new { success = false, message = "Oops! Something went wrong, please try again later" }, JsonRequestBehavior.AllowGet); }
            }
            return View("AddNewVacation", vacation);

        }

        public ActionResult UpdateVacations(VacationInsertAndEdit vacation, HttpPostedFileBase file) {
            try
            {
                if (ModelState.IsValid)
                {
                    if (file != null && !CheckContentType(file.ContentType))
                    {
                        return Json(new { success = false, message = "File format is not supported, please upload a PDF file!" }, JsonRequestBehavior.AllowGet);
                    }
                    else if (file != null && file.ContentLength > 0)
                    {
                        try
                        {
                            string path = vacation.Attatchment;

                            path = Path.Combine(Server.MapPath("/Content/Files"),
                                                       Path.GetFileName(file.FileName));
                            file.SaveAs(path);
                            vacation.Attatchment = path;

                            ViewBag.Message = "File uploaded successfully";
                        }
                        catch (Exception ex)
                        {
                            GlobalVariable.log.Error(ex);
                         //   ViewBag.Message = "ERROR:" + ex.Message.ToString();
                        }
                    }
                    if (vacation.RejectionReason == null && vacation.Status == Statuses.Rejected)
                    {
                        return Json(new { success = false, message = "Reason field is required" });
                    }
                        HttpResponseMessage response = GlobalVariable.ApiClient.PutAsJsonAsync<VacationInsertAndEdit>($"vacations/PutVacation/{vacation.VacationID}", vacation).Result;

                    if (response.IsSuccessStatusCode)
                    {
                        return Json(new { success = true, message = "Updated" });
                    }
                    else
                    {
                        return Json(new { success = false, message = "Not Found" });

                    }
                }
            }
            catch (Exception ex) {
                GlobalVariable.log.Error(ex.Message); 
                return Json(new { success = false, message = "Oops! Something went wrong, please try again later" }, JsonRequestBehavior.AllowGet); 
            }
            return View("UpdateVacation");
        }
        [HttpPost]
        public ActionResult DeleteVacation(int id)
        {
            try
            {

MVCforHRSystem/Views/User/AddNewEmployee.cshtml
@model HR.Website.Models.UserInsertAndEdit
@{
    Layout = null;
    ViewBag.Title = "AddNewEmployee";
}

<!DOCTYPE html>
<head>
    <link href="~/Content/alertify.css" rel="stylesheet" />
</head>
<html>

<body>

    @using (Html.BeginForm("AddUser", "User", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
    {

        <h1>Add New Employee</h1>
        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-md-offset-2 col-md-10">
                <input id="btnSubmit" type="submit" value="Add" class="btn btn-info" />
                <input id="btnReset" type="reset" value="Reset" class="btn btn-warning" />
            </div>
        </div>
    }




    @*</form>*@
    @*<div class="modal fade" tabindex="-1" id="successModel"
             data-keyboard="false" data-backdrop="static">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            &times;
                        </button>
                        <h4>Success</h4>
                    </div>
                    <div class="modal-body">
                        <h2>Added Successfully</h2>
                    </div>
                    <div class="modal-footer">
                        <button type="button" data-dismiss="modal" class="btn btn-success">
                            Close
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('#btnSubmit').click(function () {
                    $('#successModel').modal('show');

                });

            });

        </script>*@
    @*<script src="~/Scripts/alertify.js"></script>
        <script src="~/Scripts/alertify.min.js"></script>
        <script src="~/Scripts/jquery-3.4.1.min.js"></script>

        <script>

                                    //$('#btnSubmit').click(function () {
                                    //    alertify.confirm("This is a confirm dialog.",
                                    //        function () {
                                    //            alertify.success('Ok');
                                    //        },
                                    //        function () {
                                    //            alertify.error('Cancel');
                                    //        });
                                    //});

                                    //var pre = document.createElement('pre');
                                    ////custom style.
                                    //pre.style.maxHeight = "400px";
                                    //pre.style.margin = "0";
                                    //pre.style.padding = "24px";
                                    //pre.style.whiteSpace = "pre-wrap";
                                    //pre.style.textAlign = "justify";
                                    //pre.appendChild(document.createTextNode($('#addForm').text()));
                                    ////show as confirm
                                    //alertify.confirm(pre, function () {
                                    //    alertify.success('Add');
                                    //}, function () {
                                    //    alertify.error('Cancel');
                                    //}).set({ labels: { ok: 'Added', cancel: 'Canceled' }, padding: false });


        </script>*@

</body>
</html>

MVCforHRSystem/Views/User/DisplayUsers.cshtml
@model IEnumerable<HR.Website.Models.UserView>

@{
    ViewBag.Title = "GetUsers";
}
<!DOCTYPE html>
<head>
    <link href="//cdn.datatables.net/1.10.21/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link herf="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/alertify/alertify.core.css" rel="stylesheet" />
    <link href="~/Content/alertify/alertify.default.css" rel="stylesheet" />
</head>
<html>
<body>
    <h2>Employees</h2>

    <a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddNewEmployee","User")')"> + Add New</a>
    <table class="table table-striped table-bordered" id="datatable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.UserID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.JobTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Mobile)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    Operations
                </th>
            </tr>
        </thead>
    </table>

    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/dataTable.js" type="text/javascript"></script>
    <script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="//cdn.datatables.net/1.10.21/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/alertify/alertify.js"></script>
    <script src="~/Scripts/alertify/alertify.min.js"></script>
    <script src="~/Scripts/FormProccessing.js"></script>
    <script type="text/javascript">
        var dataTable;
        $(document).ready(function () {
            //$.noConflict();
            dataTable =  $('#datatable').DataTable({

                ajax: {
                    "url": "/User/GetUsers",
                    "type": "POST",
                    "dataSrc": "aaData",
                    "datatype": "json",
                    
                },

                "serverSide": true,
                "order": [[0, 'asc']],
                "processing": true,
                "lengthMenu": [[5, 10, 20, 50], [5, 10, 20, 50]],
                "paging": true,

                "columnDefs": [{
                    "targets": 6,
                    "data": "UserID",
                    "render": function (data, type, row, meta) {
                        var btn = "<a class = 'btn btn-danger btn-sm' onclick=DeleteUser("+row[0]+")>Delete</a> <a class = 'btn btn-default btn-sm' style='margin-left' onclick=PopupForm('@Url.Action("UpdateEmployee","User",new { id=-1})')> Edit</a>"
                        btn = btn.replace("-1", row[0]);
                        return btn;
                    },
                    "orderable": false,
                    "width": "150px",
                }],
            });
            $.fn.dataTable.ext.errMode = 'none';
            $('#datatable')
                .on('error.dt', function (e, settings, techNote, message) {
                    console.log('An error has been reported by DataTables: ', message);
                    alertify.error("Unable to connect to the remote server");
                })
                .DataTable();
        });
        // confirm dialog with alertify
        function DeleteUser(id) {
            alertify.confirm('Are you sure you want to delete this record?',
                    function (e) {
                        if (e) {
                               $.ajax({
                    type: "POST",
                    url: '@Url.Action("DeleteUser","User")/' + id,
                    success: function (data) {
                        if (data.success) {
                            $('#datatable').DataTable().ajax.reload();
                            alertify.success('Deleted Successfully');
                        }
                                   
                        else { alertify.error(data.message); }
                     }
                });
                        }
                        else {
                            alertify.error('Canceled');
                        }
                    });

        }
    </script>
</body>
</html>

MVCforHRSystem/Views/User/UnAuthorized.cshtml
@model System.Web.Mvc.HandleErrorInfo

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UnAuthorized</title>
</head>
<body>
    <div>
        <br />
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">Access Denied</h3>
            </div>
            <div class="panel-body">
                <h3> @ViewBag.Message </h3>
            </div>
        
        </div>
    </div>
</body>
</html>

MVCforHRSystem/Views/User/UserEmployee.cshtml
@{
    ViewBag.Title = "UserEmployee";
}
<!DOCTYPE html>
<head>
    <link href="~/Content/FormStyle.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/alertify/alertify.core.css" rel="stylesheet" />
    <link href="~/Content/alertify/alertify.default.css" rel="stylesheet" />
</head>
<html>

<body>
    <br />
    <fieldset>
        @{

            if (Session["Username"] != null)
            {
                <h2> Welcom <i style="color: #18bc9c"> @Session["Username"].ToString() </i>To HR System </h2>

            }

        }
    </fieldset>

    <div class="box">
        @*<a class="btn btn-default  btn-lg btn-block" onclick="window.location('@Url.Action("DisplayVacations","Vacation")')">Vacations </a>*@
        @Html.ActionLink("Vacations", "DisplayVacations", "Vacation", null, new { @class = "btn btn-primary  btn-lg btn-block" })
        @*<a class="btn btn-primary  btn-lg btn-block" onclick=PopupForm('@Url.Action("AddNewVacation","Vacation")')> Request a vacation</a>*@
        <a class="btn btn-primary btn-lg btn-block" onclick=PopupForm('@Url.Action("UpdateEmployee","User",new { id=@Session["UserId"].ToString()})')> Edit Your Information</a>
    </div>
    @if (!string.IsNullOrEmpty(ViewBag.Message))
    {

        <script>
            alertify.error("@ViewBag.Message");
        </script>
    }

    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/alertify/alertify.js"></script>
    <script src="~/Scripts/alertify/alertify.min.js"></script>

    <script type="text/javascript">
        function redirectOnClick() {
            document.location = '@Url.Action(" DisplayUserVacations","Vacation")'
        }


        var popup;
        function PopupForm(url) {

            var formDiv = $('<div/>');
            $.get(url)
                .done(function (response) {
                    formDiv.html(response);
                    popup = formDiv.dialog({
                        autoOpen: true,
                        resizable: false,
                        height: 500,
                        width: 700,
                        close: function () {
                            popup.dialog('destroy').remove();
                        }
                    });
                });
        }

        function SubmitForm(form) {
            // to validate the form before submiting

            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                var formData = new FormData(form);
               // formData.append("file", input.files[0]);
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (data) {
                        if (data.success) {
                            popup.dialog('close');
                            $.notify(data.message, {
                                globalPosition: 'top center',
                                className: "success"
                            });
                        }
                        else {
                            $.notify(data.message, {
                                globalPosition: 'top center',
                                className: "error"
                            });
                        }

                    }

                });
            }
            return false

        }

    </script>

</body>
</html>

MVCforHRSystem/Views/User/UserManager.cshtml
@{
    ViewBag.Title = "UserManager";
}

<!DOCTYPE html>
<head>
    <link href="~/Content/FormStyle.css" rel="stylesheet" />
    <link type="text/css" href="~/Content/alertify.css" rel="stylesheet" />
</head>
<html>

<body>
    <br />
        @{

            if (Session["Username"] != null)
            {
                <h2> Welcom <i style="color: #18bc9c">@Session["Username"].ToString()</i> To HR System </h2>

            }

        }


<div class="box">

    @Html.ActionLink("Vacations", "DisplayVacations", "Vacation", null, new { @class = "btn btn-primary  btn-lg btn-block" })
    @Html.ActionLink("Display all Employees", "DisplayUsers", null, new { @class = "btn btn-primary  btn-lg btn-block" })

</div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/alertify.js"></script>
    <script src="~/Scripts/alertify.min.js"></script>
    <script>
     @*@{
          if (Session["Username"] != null)
           
            {
             var username = @Session["Username"].ToString();

             <text>
        alertify.warning("Welcome Back");
             </text>

         }

        }*@
    </script>


    @*<form action="/user/AddUser" method="post" id="addForm">
            <h1>Add New Employee</h1>
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ManagerID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ManagerID, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ManagerID, "", new { @class = "text-danger" })
                    </div>

                </div>

                <div class="col-md-offset-2 col-md-10">
                    <input id="btnSubmit" type="submit" value="Add" class="btn btn-default" />
                </div>
            </div>

        </form>*@
</body>
</html>